apiVersion: v1
kind: ConfigMap
metadata:
  name: colibris-configmap
data:
  database_url: mongodb://db:27017/Colibris?retryWrites=true&w=majority
  user_service: https://user:5001/
  appointment_service: https://appointment:5000/