apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: colibris
  namespace: colibris
spec:
  rules:
  - host: colibris.creometry.dev
    http:
      paths:
      
        - path: /
          pathType: Prefix
          backend:
            service:
              name: index
              port: 
                number: 80
        - path: /profile
          pathType: Prefix
          backend:
            service:
              name: user
              port: 
                number: 5001
        - path: /schedule
          pathType: Prefix
          backend:
            service:
              name: schedule
              port: 
                number: 5000    
  tls: 
  - hosts:
    - colibris.creometry.dev

    secretName: colibris-front-ingress