apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      run: front
  replicas: 1
  template:
    metadata:
      labels:
        run: front
    spec:
      containers:
      - name: front
        image: colibristn/front:v0.1.1
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_GOOGLE_API_KEY
            valueFrom:
              configMapKeyRef:
                name: colibris-configmap
                key: google_key 
---
apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    run: front
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: front
