apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: colibris
  name: index
spec:
  selector:
    matchLabels:
      run: index
  replicas: 1
  template:
    metadata:
      labels:
        run: index
    spec:
      containers:
      - name: customerui
        image: colibristn/customerui:v0.2.4
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /usr/share/nginx/html/config.js
            readOnly: true
            subPath: config.js
      volumes:
      - name: config
        configMap:
          name: colibris-configmap

---
apiVersion: v1
kind: Service
metadata:
  namespace: colibris
  name: index
  labels:
    run: index
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: index
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: colibris
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - test-colibris.creometry.dev
    - colibristunisie.com
   
  rules:
  - host: test-colibris.creometry.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: colibris-front-svc
            port:
              number: 80
  - host: colibristunisie.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: colibris-front-svc
            port:
              number: 80