apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: colibris
  name: index
spec:
  selector:
    matchLabels:
      run: index
  replicas: 1
  template:
    metadata:
      labels:
        run: index
    spec:
      containers:
      - name: front
        image: colibristn/front:v0.1.1
        ports:
        - containerPort: 80
        env:
          - name: REACT_APP_USER_SERVICE_URI
            valueFrom:
              configMapKeyRef:
                name: colibris-configmap
                key: user_service
          - name: REACT_APP_APPOINT_SERVICE_URI
            valueFrom:
              configMapKeyRef:
                name: colibris-configmap
                key: appointment_service
---
apiVersion: v1
kind: Service
metadata:
  namespace: colibris
  name: index
  labels:
    run: index
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: index
