apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ratings
  name: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ratings
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/test: "true"
        io.kompose.service: ratings
    spec:
      containers:
        - env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: colibris-configmap
                  key: postgres_database_url
          image: colibristn/ratingservice
          name: ratings
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ratings
  name: ratings
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: ratings
status:
  loadBalancer: {}
