apiVersion: apps/v1
kind: Deployment
metadata:
  name: colibris-schedule-deploy
#  namespace: colibris
spec:
  selector:
    matchLabels:
      app: colibris-schedule
  replicas: 1
  template:
    metadata:
      labels:
        app: colibris-schedule
        project: colibris
    spec:
      containers:
      - name: schedule
        image: colibristn/schedule:v0.2.2
        ports:
        - containerPort: 5000
        env:
          - name: ATLAS_URI
            valueFrom:
              configMapKeyRef:
                name: colibris-configmap
                key: ATLAS_URI
          - name: USER_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: colibris-configmap
                key: USER_SERVICE
          - name: MAX_APPS
            valueFrom:
              configMapKeyRef:
                name: colibris-configmap
                key: MAX_APPS
          
---
apiVersion: v1
kind: Service
metadata:
  name: colibris-schedule-svc
  labels:
    project: colibris
#  namespace: colibris
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: colibris-schedule
