apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: colibris
spec:
  selector:
    matchLabels:
      run: user
  replicas: 1
  template:
    metadata:
      labels:
        run: user
    spec:
      containers:
      - name: user
        image: colibristn/user:v0.2.2
        ports:
        - containerPort: 5001
        env:
          - name: ATLAS_URI
            valueFrom:
              configMapKeyRef:
                name: colibris-configmap
                key: ATLAS_URI 
          - name: GOOGLE_API_KEY
            valueFrom:
              configMapKeyRef:
                name:  colibris-configmap
                key: GOOGLE_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    run: user
spec:
  ports:
  - port: 5001
    protocol: TCP
  selector:
    run: user
  
