//GENERATED BY go-create
package routes

import (
	c "github.com/creometry-incubator/colibris/controllers"
	"github.com/gofiber/fiber/v2"
)

func PublicRoutes(app *fiber.App) {
	app.Get("/ratings",c.GetRatings)
	app.Get("/ratings/:id",c.GetRatingById)
	app.Get("/ratings/user/:user_id",c.GetRatingByUserId)
	app.Post("/ratings",c.CreateRating)
	app.Put("/ratings",c.UpdateRating)
	app.Delete("/ratings/:id",c.DeleteRating)

}