//GENERATED BY go-create
package database

import (
	"os"

	"github.com/creometry-incubator/colibris/models"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

var DB *gorm.DB = nil

func InitializeDB() {
	database, err := gorm.Open(postgres.Open(os.Getenv("DB_URL")),&gorm.Config{})
	if err != nil {
		panic(err)
	}
	if err=database.AutoMigrate(&models.Rating{});err != nil{
		panic(err)
	}
	 DB = database
}