//GENERATED BY go-create
package models

type Rating struct {
	ID              int `json:"id"`
	PickupRequestID int `json:"pickup_request_id"`
	UserId          int `json:"user_id"`
	Quality         int `json:"quality"`
	Quantity        int `json:"quantity"`
	Treatment       int `json:"treatment"`
}
