//GENERATED BY go-create
package models


type Rating struct {
	UUID              string `gorm:"primaryKey"`
	PickupRequestID string `json:"pickup_request_id"`
	UserId          string `json:"user_id"`
	Quality         int `json:"quality"`
	Quantity        int `json:"quantity"`
	Treatment       int `json:"treatment"`
}