name: customer-ui CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --production
      working-directory: customer-ui
    - run: npm test
      working-directory: customer-ui
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: colibristn/customerui
        tags: v0.2.4
        dockerfile: customer-ui/Dockerfile
        registry: docker.io
        directory: customer-ui
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.COLIBRIS_TOKEN }}
