name: Ratings Service CI

on:
  push:
    branches: [ratings]
  pull_request:
    branches: [ratings]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
      - run: go test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: colibristn/ratingsService
          tags: v1.0.0, latest
          dockerfile: ratings/Dockerfile
          registry: docker.io
          directory: ratings
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.COLIBRIS_TOKEN }}
