name: Zone Service CI

on:
  pull_request:
    branches: [ dev ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --production
      working-directory: zone-coverage-service
    - run: npm test
      working-directory: zone-coverage-service
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: colibristn/zone
        tags: v0.2.2
        dockerfile: zone-coverage-service/Dockerfile
        registry: docker.io
        directory: zone-coverage-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.COLIBRIS_TOKEN }}
