version: '3'
services:
  zone-coverage:
    build: 
      context: .
      args :
        NODE_ENV: development
    ports: 
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MONGO_USER=mohamed
      - MONGO_PASSWORD=colibris
      - GOOGLE_API_KEY=AIzaSyDoDpVoO9zkkAwUIDI3DUot_MbXb8juqhA
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mohamed
      - MONGO_INITDB_ROOT_PASSWORD=colibris
   
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: